'use strict';
console.log('This is index.js1')
console.log('This is index.js2')
console.log('This is index.js3')
console.log('This is index.js4')
console.log('This is index.js5')
console.log('This is index.js6')
console.log('This is index.js7')
console.log('This is index.js8')
console.log('This is index.js9')
console.log('This is index.js10')
console.log('This is index.js11')
console.log('This is index.js12')
console.log('This is index.js13')
console.log('This is index.js14')
console.log('This is index.js15')
console.log('This is index.js16')